# Generated by Django 4.2.3 on 2023-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
                ('Phone', models.BigIntegerField()),
                ('Images', models.ImageField(upload_to='image')),
                ('Resume', models.FileField(upload_to='resume')),
            ],
        ),
    ]
