# Generated by Django 4.2.3 on 2023-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Images',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Resume',
            field=models.FileField(upload_to=''),
        ),
    ]
