# Generated by Django 4.2.3 on 2023-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_employees_images_alter_employees_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Images',
        ),
    ]
