# Generated by Django 4.2.3 on 2023-07-10 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_remove_employees_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Resume',
            field=models.FileField(upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'jpg', 'png'])]),
        ),
    ]
