# Generated by Django 4.2.3 on 2023-07-10 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_employees_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Images',
            field=models.FileField(default='', upload_to='image/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'jpg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='Resume',
            field=models.FileField(upload_to='resume/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'jpg', 'png'])]),
        ),
    ]
