# Generated by Django 4.2.3 on 2023-07-10 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_employees_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Images',
            field=models.FileField(upload_to='image/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Resume',
            field=models.FileField(upload_to='resume/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'jpg', 'png', 'jpeg'])]),
        ),
    ]
