# Generated by Django 4.2.3 on 2023-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_alter_employees_images_alter_employees_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='City',
            field=models.CharField(choices=[('New Delhi', 'New Delhi'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Patna', 'Patna'), ('Pune', 'Pune '), ('Hyderabad', 'Hyderabad'), ('Bhubaneswar', 'Bhubaneswar'), ('Kochi', 'Kochi'), ('Lucknow', 'Lucknow'), ('Ahmedabad', 'Ahmedabad')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
