# Generated by Django 4.2.3 on 2023-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_alter_employees_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='City',
            field=models.CharField(choices=[('New Delhi', 'New Delhi'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Patna', 'Patna'), ('Pune', 'Pune '), ('Hyderabad', 'Hyderabad'), ('Bhubaneswar', 'Bhubaneswar'), ('Kochi', 'Kochi'), ('Lucknow', 'Lucknow'), ('Ahmedabad', 'Ahmedabad')], max_length=20),
        ),
    ]
